### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by iocmet** [KindRedSand/Terraria.ModKit#1]
add .csproj or .sln to source code please, i tried to decompile the release through ILSpy and use .csproj from there, but after compilation and launching, it gives me an error
![Discord_LajbSPMDNl](https://user-images.githubusercontent.com/63492966/130320615-d6c14e76-6211-436d-b8a9-b60683b07a17.png)

**Comment by KindRedSand** [comment]
Added .csproj in latest commit
https://github.com/KindRedSand/Terraria.ModKit/commit/307e1687a873ca652943cf9f4a13bb4ea4757cdf
