### ISSUE TITLE
New version terraria 1.4.3.1 crash

### ISSUE THREAD

**Issue by wermex** [KindRedSand/Terraria.ModKit#3]
Crash occurs when entering the world. I am using the latest version of the mod (ModKit v0.6). Please correct the error, thanks in advance) @KindRedSand

**Comment by KindRedSand** [comment]
Hope new release will fix it, since i can't reproduce this bug anymore

**Comment by wermex** [comment]
FIXED :)

**Comment by wermex** [comment]
When I teleport to a friend's server (Using a map), the same error flies as before with entering the world
![Terraria ModKit_Zeob5EiR2E](https://user-images.githubusercontent.com/50787270/143215842-2cfee690-e6ad-4245-aa53-d8b688cd3d1a.png)
PS I have not found any problems in a single player game yet
As I understand it, this error appears with a variety of actions (TP, and more)
When changing the bind of the flight
