### ISSUE TITLE
just 2 questions

### ISSUE THREAD

**Issue by zcn15** [KindRedSand/Terraria.ModKit#5]
Hi, how can I change key binds for fly and unlock items in journey menu and is it possible?
Also, where I can read all command list for REPL? I just want to find command for inf summons and cant find it ingame

**Comment by KindRedSand** [comment]
Most keybinds can be changed in control settings (last panel). 
For REPL you can use, for example, Visual Studio, create a C# project (or clone this repo), add Terraria.exe as library and inspect namespaces and static accessible values by IntelliSense hints
