### ISSUE TITLE
menu not opening.

### ISSUE THREAD

**Issue by therandomdudejajaja** [KindRedSand/Terraria.ModKit#9]
i pressed num0 several times but it doesnt open the god mode and stuff menu, any ideas why?

**Comment by KindRedSand** [comment]
Are you shure you launched game using mod file? You can check if mod is loaded by looking at version in lower left corner in main menu.
![versionstring](https://github.com/KindRedSand/Terraria.ModKit/assets/27924156/ac13f5cd-0006-4343-bef2-1878ed381691)


If mod is loaded but you still dont see menu set in game Zoom to 100% bc panel can be outside of camera view. 
![zoom](https://github.com/KindRedSand/Terraria.ModKit/assets/27924156/4e4197ec-842c-49d5-8b0e-f79eec07d28b)

**Comment by therandomdudejajaja** [comment]
okay i will try the zoom, sorry for that hellishly long time before response
edit: it broke when i changed it to windowed cuz im mostly streaming so i get dms a ton
when u change resolution too
edit2: zoom didnt help
edit3:
![image](https://github.com/KindRedSand/Terraria.ModKit/assets/120328764/5fb473e1-7414-45c0-b6d7-eab760d86ad3)

**Comment by BaconDave312** [comment]
it broke when i changed it to windowed cuz im mostly streaming so i get dms a ton
when u change resolution too

**Comment by therandomdudejajaja** [comment]
also, what would the next update be?

**Comment by KindRedSand** [comment]
Rn tested last release on my pc by resizng game using menu and widnow edge drags and all the time meny stay at the middle bottom. Tested with 100% zoom and borderless/windowed mode, exclusive fullscreen glitchs out once leaved for me. Can you provide your screen resolution?

About update: rn i don't have enough time to work on this mod, also tML 1.4 are out where cheat sheet/hero mod works way better imo

**Comment by therandomdudejajaja** [comment]
ok.
![image](https://github.com/KindRedSand/Terraria.ModKit/assets/120328764/560108f9-74d2-4ba3-80ed-cc112b9adc99)
![image](https://github.com/KindRedSand/Terraria.ModKit/assets/120328764/b800b1e0-4e12-4527-9f62-c5e0f1ca15d1)
edit: its left not leaved, just for other ppls to understand better
edit2: some ppl might not wanna play with tmod, some might be having a cracked game.

**Comment by KindRedSand** [comment]
Sorry for a delayed responce. I don't have ability to test this on resolution more what 1080p, but looks like at your resolution game won't allow you to have exactly 1.f zoom.

Also, i missed one property in `LegacyGameInterfaceLayer` wich by default set UI scaling relative to world isntead of UI, so now i hope i finaly get rid of this issue with ee981eb

Feel free to [test it out](https://github.com/KindRedSand/Terraria.ModKit/releases/latest)

**Comment by therandomdudejajaja** [comment]
how do i test it out? it has no terraria.modkit.exe
also sorry for a late resp

**Comment by therandomdudejajaja** [comment]
also it is not buttons unclickable, its the gui not opening.

**Comment by therandomdudejajaja** [comment]
the pre-last (aka last with an exe) release worked, tysm

**Comment by therandomdudejajaja** [comment]
the buttons were actually unclickable, srry

**Comment by KindRedSand** [comment]
Looks like i forgot to attach a new version where issue with btns are fixed. Uploaded to latest last version

**Comment by therandomdudejajaja** [comment]
ight

**Comment by therandomdudejajaja** [comment]
KingRedSand, the REPL isnt working.

**Comment by therandomdudejajaja** [comment]
maybe you will try adding stuffs like in heros mod like no weapon cd and others?

**Comment by therandomdudejajaja** [comment]
i really hope you do not stop working on this, hundreds of people use it and without this vanilla trolling and ease of building will collapse, im sure that nobody wants that to discontinue on this stage of dev. keep up the good job, i love this.
